### ISSUE TITLE
Team gold/xp advantage very difficult to see

### ISSUE THREAD

**Issue by jacquesh** [jacquesh/VisualizAncients#14]
We currently have 2 bars extending from the edges inwards, it would almost certainly be better to have a single var that extends outwards from the centre and only shows the advantage (IE only 1 team will have a non-zero bar for each of gold and XP) instead of the absolute value (since the advantage is the only thing anybody cares about)

**Comment by Voodoodrood** [comment]
Maybe have the advantage as a colored bar from the center outwards but also have the totals (for both teams) greyed out behind that (also from center for consistency). Useful to give scale to the advantage i.e. if the advantage is 1% of total gold earned or 30% is something you'd be interested in and isn't immediately obvious otherwise.

**Comment by jacquesh** [comment]
At the same time though, I can tell you that for example a 5k lead at 15 minutes is really big but I have NO CLUE what percentage of the total worth that equates to because the game never tells you that information. So I don't know if it'd be quite that useful but hey, if theres no reason to leave it out then go for it.
